# Support the author by using the funding links below:
# https://buymeacoffee.com/weseklund


github: weklund
buy_me_a_coffee: weseklund

# Your support means a lot to me to continue development of open source projects like this one.
