name: CI

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  cache-and-install:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: SKIP_POSTINSTALL=1 bun install

      - name: Run Eslint
        run: bun run lint

      - name: Run Tests and get Coverage
        run: bun run coverage

      - uses: coverallsapp/github-action@v2.2.3
        name: Coveralls GitHub Action

      - name: Run Prettier check
        run: bun run check-format
