name: Release
on:
  workflow_run:
    workflows: [tests]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.ref_name == 'main' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - run: codfish/semantic-release-action@v3
        with:
          dry-run: true
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major'
            ]
          repository-url: https://github.com/weklund/alfred-chrono-notes.git
          tag-format: "v${version}"
          extends: "@semantic-release/apm-config"
          additional-packages: |
            ['@semantic-release/apm@4.0.0', '@semantic-release/git']
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@semantic-release/apm', '@semantic-release/git']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
