name: Release
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.ref_name == 'main' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: SKIP_POSTINSTALL=1 npm i
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          dry_run: true
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
